                        	<li>
                            	<figure>
                                	<a href="javascript:alert('link to album');" class="frame" title="Intel 10 代 Core 筆記型電腦平台再添八款 14nm Comet Lake ，為主流輕薄筆電提供最高 6 核心的純性能處理器"><img src="/assets_front/images/sample/Chalcanthite-1200x784.jpg" class="FxLoadAndCenter preload"><span class="frameBroder"></span></a>
                                    <figcaption><a href="javascript:;" title="Intel 10 代 Core 筆記型電腦平台再添八款 14nm Comet Lake ，為主流輕薄筆電提供最高 6 核心的純性能處理器">Intel 10 代 Core 筆記型電腦平台再添八款 14nm Comet Lake ，為主流輕薄筆電提供最高 6 核心的純性能處理器</a></figcaption>
                                </figure>
                            </li>