                        <p>
                            開車路線</p>
                        <p>
                            　　國道1號圓山交流道下&rarr;濱江街&rarr;大直橋&rarr;北安路&rarr;北安路圓環&rarr;北安路&rarr;自強隧道&rarr;自強橋&rarr;故宮路&rarr;至善路2段&rarr;至善路3段&rarr;法雨山普宜苑。</p>
                        <p>&nbsp;
                            </p>
                        <p>
                            公車&nbsp;<strong><span style="color:#ff0000;"><span style="font-size:18px;">(小18)&nbsp;</span></span></strong><span style="font-size:18px;"><span style="font-size:16px;">行經路線</span></span></p>
                        <p>
                            &nbsp; &nbsp;1.捷運劍潭站(基河)&rarr;2.陽明戲院&rarr;3.小北街&rarr;4.士林區農會&rarr;5.捷運士林站(中正)&rarr;6.福林國小&rarr;7. 士林官邸(中正)&rarr;8.泰北中學&rarr;9.雙溪公園&rarr;10.梅林新村&rarr;11.東吳大學(錢穆故居)&rarr;12.外雙溪(至善)&rarr;13.故宮博物院&rarr;14.衛理女中(原住民&hellip;)&rarr;15.至善國中&rarr;16.雙溪別墅&rarr;17.劍南僑&rarr;18.大經橋&rarr;19.外雙溪橋&rarr;20.內雙溪橋&rarr;21. 至善路三段&rarr;22. 碧溪橋&rarr;23. 沙崙&rarr;<span style="font-size: 18px;"><span style="color:#ff0000;">24.礁坑橋(法雨山普宜苑)</span></span></p>
                        <div>
                            &nbsp;</div>
                        <div>
                            本寺傳承臨濟宗、曹洞宗（尼眾道場）.</div>
                        <div>
                            &nbsp;</div>
                        <div>
                            地址：111台北市士林區至善路3段181巷3號</div>
                        <p>
                            電話：02－28413393&nbsp;</p>
