            <!-- 網站主選單 begin -->
            <nav class="siteMenu">
            	<div class="menuCover closeMenu"></div>
                <ul class="">
                    <li><a href="about.html" title="關於普宜苑">關於普宜苑</a></li>
                    <li><a href="news.html" title="最新消息">最新消息</a></li>
                    <li><a href="album.html" title="活動記錄">活動記錄</a></li>
                    <li><a href="information.html" title="法語原地">法語園地</a></li>
                    <li><a href="http://211.23.178.6/school001/opac/" title="圖書館">圖書館</a></li>
                    <li><a href="javascript:alert('link');" title="回到首頁">回到首頁</a></li>
                </ul>
                <a href="javascript:alert('link');" target="_blank" class="FBpage" title="臉書粉絲頁"><span class="hideItem">臉書粉絲頁</span></a>
                <button type="button" class="menuIOBtn openMenu"><i class="icon-menu"></i><i class="icon-cross"></i><span class="hideItem">選單按鈕</span></button>
            </nav>
            <!-- 網站主選單 end -->