<!-- triditional meta tags begin -->
<meta name="description" content="法雨山普宜苑(puyiyuan)，座落於台北市士林區近郊的佛寺，沿著故宮至善路三段前行，一路上伴隨著綠水青山，彷若進入超出凡塵的另一靈山勝境。山寺中，溪谷邊，經常綿綿細雨，法雨繽紛。以照印法師等人所帶領的"普宜苑"尼僧團，是以農淨（出坡念佛）修行為要務，三根普被弘揚佛法為本寺宗旨。
台北市至善路三段181巷3號   No.3, Lane 181, Sec. 3, Jhihshan Rd., Shihlin District, Taipei City 111, Taiwan (R.O.C.)   Tel: 02-28413393" />
<meta name="copyright" content="Copyright © 2019法雨山普宜苑" />
<!-- triditional meta tags end -->
<!-- open graph protocol meta tags begin -->
<meta property="og:title" content="法雨山普宜苑" />
<meta property="og:description" content="法雨山普宜苑(puyiyuan)，座落於台北市士林區近郊的佛寺，沿著故宮至善路三段前行，一路上伴隨著綠水青山，彷若進入超出凡塵的另一靈山勝境。山寺中，溪谷邊，經常綿綿細雨，法雨繽紛。以照印法師等人所帶領的"普宜苑"尼僧團，是以農淨（出坡念佛）修行為要務，三根普被弘揚佛法為本寺宗旨。
台北市至善路三段181巷3號   No.3, Lane 181, Sec. 3, Jhihshan Rd., Shihlin District, Taipei City 111, Taiwan (R.O.C.)   Tel: 02-28413393" />
<meta property="og:site_name" content="Pu-yi-yuan" />
<meta property="og:url" content="http://www.pu-yi-yuan.org.tw/" />
<!--
<meta property="og:image:type" content="image/jpeg" />
<meta property="og:image:width" content="" />
<meta property="og:image:height" content="" />
<meta property="og:image" content="" />
-->
<!-- open graph protocol meta tags begin -->
<!-- triditional meta tags begin --
<link rel="image_src" type="image/jpeg" />
-- triditional meta tags end -->