                	<div class="posterWrapper">
                        <div class="frameTop"><img src="/assets_front/images/slideText01.png"></div>
                        <figure class="frameMiddle"><a href="/assets_front/images/201904201648307979.jpg" target="_blank"><img src="/assets_front/images/201904201648307979.jpg"></a></figure>
                        <div class="frameBottom"><img src="/assets_front/images/slideText02.png"></div>
                    </div>