<div id="pingForRwd"><p><!-- RWD check --></p></div>
<!-- 背景音樂 begin -->
<div class="BGplayer">
	<audio controls preload="metadata" loop autoplay id="bgMusic">
		<source src="/assets_front/images/bg.mp3" type="audio/mpeg">
	</audio>
	<button type="button" class="closeHintBg" data-task="closeHint"><span>關閉</span></button><button type="button" class="playBg" data-task="playMusic"><span class="text">播放背景音樂</span><span class="author">亞洲唱片授權：[自性彌陀]　NO.1 金山活佛念佛</span></button>
</div>
<!-- 背景音樂 end -->