                        	<li>
                            	<figure>
                                	<a href="https://www.youtube.com/watch?v=BHRFBKjqEvg" class="frame" title="How to Make Borax Crystals">
										<img src="https://img.youtube.com/vi/BHRFBKjqEvg/3.jpg" class="FxLoadAndCenter preload">
										<span class="frameBroder video"></span>
									</a>
                                    <figcaption>
										<span title="How to Make Borax Crystals">How to Make Borax Crystals</span>
									</figcaption>
                                </figure>
                            </li>