                    <nav class="mobileSideOption">
                    	<div class="labelBox">
                        	<span class="unitTitle"></span><!-- 單元名稱 -->
		                    <span>：</span>
                            <span class="pageTitle"></span><!-- 網頁名稱 -->
                            <div class="ink"></div>
                        </div>
                    	<ul><!-- 動態加入 --></ul>
                    	<button type="button" class="menuIOBtn menuClose"><i class="icon-triangle-down"></i><i class="icon-triangle-up"></i><span class="hideItem"></span></button>
                    </nav>