                    <div class="subsetList">
                    	<h3>【108年與您道上有約】</h3>
                        <ol>
                            <li><a href="javascript:;" title="2019/04/02 Intel 10 代 Core 筆記型電腦平台再添八款 14nm Comet Lake ，為主流輕薄筆電提供最高 6 核心的純性能處理器"><time datetime="2019-04-02">2019/04/02</time>Intel 10 代 Core 筆記型電腦平台再添八款 14nm Comet Lake ，為主流輕薄筆電提供最高 6 核心的純性能處理器</a></li>
                            <li><span class="current" title="2019/04/02 LINE新版介面開放更新 好友、官方帳號清楚區分 Android版本率先推出"><time datetime="2019-04-02">2019/04/02</time>LINE新版介面開放更新 好友、官方帳號清楚區分 Android版本率先推出</span></li><!-- 目前頁面無連結 -->
                            <li><a href="javascript:;" title="2019/04/02 Steam推出中國專屬獨立服務「蒸汽平台」"><time datetime="2019-04-02">2019/04/02</time>Steam推出中國專屬獨立服務「蒸汽平台」</a></li>
                            <li><a href="javascript:;" title="2019/04/02 Sony A7R IV 數位麥克風"><time datetime="2019-04-02">2019/04/02</time>Sony A7R IV 數位麥克風</a></li>
                            <li><a href="javascript:;" title="2019/04/02 Sony 微軟釋出Chromium架構的新Edge瀏覽器beta測試版本 未來將持續降低CPU與記憶體資源佔用"><time datetime="2019-04-02">2019/04/02</time>微軟釋出Chromium架構的新Edge瀏覽器beta測試版本 未來將持續降低CPU與記憶體資源佔用</a></li>
                        </ol>
                    </div>