        <footer>
            <div class="box">
                <address>
                    <span class="add">台北市至善路三段181巷3號</span>
                    <span class="add pc-ignore">|</span>
                    <span lang="en" class="add tablet-ignore phone-ignore">No.3, Lane 181, Sec. 3, Jhihshan Rd., Shihlin District, Taipei City 111, Taiwan (R.O.C.)</span><br class="pc-ignore tablet-ignore phone-ignore"><span class="add">Tel: 02-28413393</span>
                </address>
                <span class="cprs">Copyright &copy; 2019法雨山普宜苑</span>
            </div>
        </footer>